import { type Metadata } from "next";
import Link from "next/link";

import { PublicFooter } from "~/app/_components/public-footer";
import { resolveShareForDisplay, shareInitials } from "~/server/public-share";
import "~/app/_components/public-site.css";

// P26-10: public landing page for a vCard share link. Replaces the old direct
// .vcf download (now at /share/{token}/vcard) so the link unfurls with a branded
// preview on WhatsApp/iMessage/Twitter (og:image is generated by the sibling
// opengraph-image.tsx) and offers a friendly download.

type Props = { params: Promise<{ token: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params;
  const share = await resolveShareForDisplay(token);
  if (share.status !== "ok") {
    return { title: "Shared contact", robots: { index: false }, alternates: { canonical: `/share/${token}` } };
  }
  return {
    title: `${share.name} shared a contact card`,
    description: `${share.name}${share.secondary ? ` · ${share.secondary}` : ""} — open to save this contact to your address book.`,
    robots: { index: false },
    alternates: { canonical: `/share/${token}` },
  };
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <div className="kx">
      <main className="flex min-h-dvh flex-col">
        <div className="flex flex-1 items-center justify-center px-4 py-12">{children}</div>
        <PublicFooter />
      </main>
    </div>
  );
}

export default async function SharePage({ params }: Props) {
  const { token } = await params;
  const share = await resolveShareForDisplay(token);

  if (share.status !== "ok") {
    const message =
      share.status === "revoked"
        ? "This share link has been revoked by its owner."
        : share.status === "expired"
          ? "This share link has expired."
          : "This share link is no longer available.";
    return (
      <Shell>
        <div className="flex w-full max-w-[420px] flex-col items-center rounded-[18px] border border-[#e9ece7] bg-white px-7 py-12 text-center shadow-[0_20px_60px_rgba(20,30,25,0.08)]">
          <span className="grid h-12 w-12 place-items-center rounded-xl bg-[#17352e] text-[20px] font-bold text-[#dff0e7]">
            K
          </span>
          <h1 className="mt-5 text-[20px] font-semibold text-[#1d2823]">Link unavailable</h1>
          <p className="mt-2 text-[14px] leading-[1.55] text-[#5c655e]">{message}</p>
          <Link
            className="mt-6 inline-flex h-11 items-center rounded-[10px] bg-[#4158f4] px-5 text-[14px] font-semibold text-white transition hover:bg-[#3347d8]"
            href="/"
          >
            Learn about Kontax
          </Link>
        </div>
      </Shell>
    );
  }

  return (
    <Shell>
      <div className="flex w-full max-w-[440px] flex-col items-center rounded-[18px] border border-[#e9ece7] bg-white px-7 py-10 text-center shadow-[0_20px_60px_rgba(20,30,25,0.08)]">
        <div className="flex items-center gap-2 text-[13px] font-medium text-[#8b938c]">
          <span className="grid h-6 w-6 place-items-center rounded-md bg-[#17352e] text-[12px] font-bold text-[#dff0e7]">
            K
          </span>
          Shared via Kontax
        </div>

        <span className="mt-7 grid h-20 w-20 place-items-center rounded-full bg-[#e7efe9] text-[26px] font-semibold text-[#17352e]">
          {shareInitials(share.name)}
        </span>
        <h1 className="mt-4 text-[24px] font-semibold tracking-[-0.01em] text-[#1d2823]">
          {share.name}
        </h1>
        {share.secondary ? (
          <p className="mt-1 text-[14px] text-[#5c655e]">{share.secondary}</p>
        ) : null}

        <a
          className="mt-7 inline-flex h-11 items-center gap-2 rounded-[10px] bg-[#4158f4] px-5 text-[14px] font-semibold text-white transition hover:bg-[#3347d8]"
          href={`/share/${token}/vcard`}
        >
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
            <path d="M12 4v12M7 11l5 5 5-5M5 20h14" />
          </svg>
          Save contact (.vcf)
        </a>
        <p className="mt-3 text-[12.5px] text-[#8b938c]">
          Adds {share.name} to your phone or address book.
        </p>
      </div>
    </Shell>
  );
}
